### ISSUE TITLE
Scrolling does not work in Firefox

### ISSUE THREAD

**Issue by zzeebbii** [SurenAt93/monaco-react#13]
Hello,
Right now there is a known bug with Firefox in Monaco editor. Scrolling is not working in Firefox. Issue details are here.

microsoft/monaco-editor#1353

They have added it to master but new version is not released yet. I was wondering if you can provide some patch in meantime until the solution is published in new version.

**Comment by SurenAt93** [comment]
As I see [here](https://github.com/microsoft/monaco-editor/issues/1353#issuecomment-515222615) the fix is not in monaco yet; neither in master nor in other branches. So, we can't provide a patch for that. But, as you know, in the new version you can change configs and download monaco wherever you want, so, if you know there is a place with that kind of patch you can use it.
