### ISSUE TITLE
ControlledEditor not remove css color properties

### ISSUE THREAD

**Issue by M-Husein** [SurenAt93/monaco-react#24]
Hi,
Thank you for sharing your work, good work & amazing;)

I have a problem in the ControlledEditor component, if I change the language / mode dynamically, there is a problem in the css language. The problem is the css property that has colors with hexa, rgba or any color mode in css doesn't remove the preview color if I change to another language.

This is an example:

![2019-10-07_20-47-31](https://user-images.githubusercontent.com/19644272/66317489-cba24200-e943-11e9-89e2-fdf7e0946f21.gif)

I hope You can give some guide.

Thanks :)

**Comment by SurenAt93** [comment]
Hi @M-Husein,

Thank you for opening this issue.

There was an issue; we have already solved it. You can just update the version of the package to the latest one (at this moment it is 2.0.0).

Let me know if everything is okay.

Thank you!

**Comment by M-Husein** [comment]
Hi @SurenAt93,

Thank you for response, this issue is fixed.
But I think I found a new issue. The issue is that when I type in the editor there is a blinking effect, specifically the font / code and minimap.
This only happens in the ControlledEditor component. I think this makes UI / UX unfavorable and unexpected.

I have seen and tried on the official Playground monaco editor, this effect does not exist.

Thanks again for your response ;)

**Comment by SurenAt93** [comment]
We checked it one more time, and couldn't find the issue (for example [here is](https://codesandbox.io/s/monaco-editorreact---controlled-editor-yg5il?fontsize=14) an example of ControlledEditor with the latest version). I will kindly ask you to create a reproducible snippet to be able to check it. You can use [codesandbox](https://codesandbox.io) for that. 

Thank you! 🙂

**Comment by M-Husein** [comment]
This is my app [demo](https://codesandbox.io/s/monaco-editor-react-r90u7) 

Try typing quickly, you can see the blinking effect. Not every time but it still happens sometimes.

**Comment by Pajn** [comment]
The blinking problem can be observed in @SurenAt93 example as well. Just add more code to the editor or use a slower computer.

My guess is that this is caused by ControlledEditor recreating the `editorDidMount` callback on every render https://github.com/SurenAt93/monaco-react/blob/master/src/ControlledEditor/ControlledEditor.js#L8 which then causes Editor to recreate the monaco instance https://github.com/SurenAt93/monaco-react/blob/master/src/Editor/Editor.js#L61-L79 which then could probably be solved with a `useCallback`. Though I have not tried

**Comment by M-Husein** [comment]
Hi @Pajn ,

Good catch, I also thought that, but I must tried.
If you have tried this please share with me.

Thanks.

**Comment by SurenAt93** [comment]
Hi guys.

Let me try to explain what's exactly happened. First of all, @Pajn, you are right, the problem exists in my example too. But Editor is not recreated in every change (it would crash everything 🙂 ). Note that `createEditor` is used once in [this](https://github.com/SurenAt93/monaco-react/blob/master/src/Editor/Editor.js#L84) file, which ensures a single creation of provided function in `useCallback`.

Okay, but what's the problem? Look, usually, we are using monaco editor itself, without interfering natural behavior of the monaco. But in this case (in Controlled Editor) we want the editor to show what we exactly want. When we are pressing "x", monaco does many processes and after deciding to draw a blue "x", but we tell him to draw another thing, which leads a blinking. Note that in this particular case we are asking him to draw the same "x", but again, even doing the same thing leads to blinking in slow machines or in case of large sources. Whatever, this problem is already [discussed](https://github.com/Microsoft/monaco-editor/issues/803) a year ago and there is a workaround (basically we force additional tokenizing). I fixed it in the new version. So, I will kindly ask you to check the new version in your cases. @M-Husein please update the library version to the latest in you provided sandbox to be sure that issue is fixed.

Thank you for your support!

**Comment by M-Husein** [comment]
Hi @SurenAt93 

I have updated your library. Now it's better.

Thanks ;)

**Comment by Pajn** [comment]
Great, thank you!
