### ISSUE TITLE
Editor do not respect grid when resizing

### ISSUE THREAD

**Issue by snelsi** [SurenAt93/monaco-react#27]
Inspect this [pin](https://codesandbox.io/s/monaco-react-scale-mon52).

If you are having your Editor in a grid-parent, it would scale up properly, but it won't scale down.
It looks like the editors width and height are hardcoded into "monaco-editor" div styles.

![exmpl](https://user-images.githubusercontent.com/15171036/68343287-1e168000-00f5-11ea-9292-123d3906d102.png)

And they do not take into account the surrounding elements when resizing.

To fix this example you need to wrap the whole editor into div with `overflow: hidden;` style.

**Comment by SurenAt93** [comment]
Hello.
Here is how the styles of the editor wrapper work.

- if you are providing the height/weight, it will be right with those dimensions,

<img width="569" alt="Screen Shot 2019-11-07 at 12 55 51" src="https://user-images.githubusercontent.com/13118722/68374898-3622e980-015f-11ea-9d50-094ca46746f4.png">

- otherwise, it will fit the full size of his parent (see also the `styles` [file](https://github.com/SurenAt93/monaco-react/blob/master/src/Editor/styles.js) for pull picture)

<img width="558" alt="Screen Shot 2019-11-07 at 13 07 01" src="https://user-images.githubusercontent.com/13118722/68375092-9a45ad80-015f-11ea-833b-a443ef9f3357.png">

- plus it will follow the size of his parent

<img width="655" alt="Screen Shot 2019-11-07 at 13 09 11" src="https://user-images.githubusercontent.com/13118722/68375217-e264d000-015f-11ea-8adf-47853d6bd96d.png">

I hope it helps. Thank you!

**Comment by snelsi** [comment]
> * otherwise, it will fit the full size of his parent 

Well, that's not quite true. It will remember the largest size the parent was, and won't scale down on resize.
![ex1](https://user-images.githubusercontent.com/15171036/68397973-af7d0500-017c-11ea-9c1f-db5c7c323ed6.png)
![ex2](https://user-images.githubusercontent.com/15171036/68397938-a1c77f80-017c-11ea-87dc-b5030a108061.png)

**Comment by SurenAt93** [comment]
Hello.

Well, I inspected your example. And I can't find any issue regarding the editor wrapper (this library is React wrapper for monaco). Maybe there are problems with monaco's automaticLayout (which is by default turned on in this library). I suggest you to refer this issue in the original monaco repo.

Thank you for your support!

**Comment by snelsi** [comment]
Actually, I found a very simillar issue in original Monaco repo.
[#1482](https://github.com/microsoft/monaco-editor/issues/1482)

**Comment by felipellrocha** [comment]
@snelsi were you able to solve it?

**Comment by snelsi** [comment]
@felipellrocha 
Adding 'overflow: hidden' to the wrapper worked for me. But it was quite some time ago

**Comment by felipellrocha** [comment]
Mmmmm, it's not working for me, though I am using a `grid` instead of a `flexbox`

**Comment by felipellrocha** [comment]
Solved. For `grid`s you need to set sizing properly:

```
grid-template-columns: repeat(10, minmax(0, 1fr));
grid-template-rows: repeat(10, minmax(0, 1fr));
```
