### ISSUE TITLE
Json does not format.

### ISSUE THREAD

**Issue by xuanlongvts** [SurenAt93/monaco-react#29]
hi, i have loaded json as the image, but not format.

<img width="1610" alt="Screen Shot 2019-11-08 at 11 13 49 AM" src="https://user-images.githubusercontent.com/11780302/68449254-0801e000-0219-11ea-93dc-5012481ccf90.png">

Can you help me, thanks!

**Comment by SurenAt93** [comment]
Hello.
By default it will show what you give the editor, I mean, if the value is not a formatted json, it will not draw a formatted json.

If you want to show non-formatted json as a formatted one you can choose one of the ways to do that

1) format before you pass it as a value:

instead of
```js
value={json}
```
write
```js
value={JSON.stringify(json, null, 2)}
```

2) or, format it by editor after passing
```js
editor.getAction('editor.action.formatDocument').run();
``` 

I hope it helps. Thank you!

**Comment by xuanlongvts** [comment]
JSON.stringify(JSON.parse(JSON), null, 2)  is fine!

Thank you very much!
