### ISSUE TITLE
Exposing monaco.languages module

### ISSUE THREAD

**Issue by onatm** [SurenAt93/monaco-react#9]
Currently, there isn't a way to use `monaco.languages` module. It'd be pretty useful to expose this module or the underlying modules (`css`, `html`, `json` and `typescript`) to enable the usage of `LanguageService`.

I think the required module(s) can be returned as a part of `editorDidMount`.

https://github.com/SurenAt93/monaco-react/blob/2998b1a802f89f3441a4a5cd54b6293b3a114862/src/Editor/Editor.js#L58

**Comment by SurenAt93** [comment]
I agree; it can be useful and also, it can be easily returned from editorDidMount.
But before do it, I'll kindly ask you to tell me about your particular case, to understand and see the picture of what we need. Thank you!

**Comment by onatm** [comment]
My use case is only for `json` schema validation but it might expand to `yaml` in the future. I quickly implemented a poc by editing `Editor.js` file to make `editorDidMount` return `monacoRef` instead `editorRef.current`.

I think `typescript` type definition should also be changed because of the misleading `monaco` argument name in there. It should be `editor` instead.

**Comment by SurenAt93** [comment]
About type definition file: I have already fixed it, the new version with new documentation will be ready today.

Now about monaco.languages module. The problem is more general, and we can redefine it as "we need access to monaco instance".

In that case, returning it from editorDidMont wouldn't be the best way to do that from the semantic point of view. editorDidMount can return (and we know it returns) editor instance, which belongs to him. The monaco instance is something general and can affect all editor instances. So it would be better to export it separately. What is my suggestion:

here is a utility called "monaco", which is used by Editor/DiffEditor components to setup monaco in the user browser (see it [here](https://github.com/SurenAt93/monaco-react/blob/master/src/Editor/Editor.js#L22) and [here](https://github.com/SurenAt93/monaco-react/blob/master/src/DiffEditor/DiffEditor.js#L35) accordingly) and after that to create an instance of the editor. So, what we need it's just exporting that utility function. The usage of it will look like this:

```
import { monaco } from '@monaco-editor/react';

monaco
  .init()
  .then(monaco => /* here is the instance of monaco, so you can use the `monaco.languages` or whatever you want */)
  .catch(error => console.error('An error occurred during initialization of Monaco: ', error));
```

It can be implemented today with the new version.

**Comment by SurenAt93** [comment]
It’s done!

Could you please check the new version (1.0.8) and the new README file to see how you can use it. And let me know if it covers your needs or not.

**Comment by onatm** [comment]
using `monaco` utility covers what I need and `README` looks better now 👍

thank you @SurenAt93 🎉

**Comment by SurenAt93** [comment]
Glad to hear that.
